### ISSUE TITLE
Reference Period Filtration Issues

### ISSUE THREAD

**Issue by VTula2000** [Swirrl/ons-data-export#15]
Need to fix `Reference Period` filtration errors in below data sets

- [ ] http://cogs-staging-web.swirrlstaging.com/dataset/cube?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons_abs-catalog-entry&

- [ ] http://cogs-staging-web.swirrlstaging.com/dataset/cube?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-fdi-catalog-entry&

**Comment by Shannon95** [comment]
Reference Period filter errors in below data sets also: 

- [ ] http://cogs-staging-web.swirrlstaging.com/dataset/cube?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-total-trade-catalog-entry&


- [ ] http://cogs-staging-web.swirrlstaging.com/dataset/cube?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-sa-trade-in-goods-catalog-entry&

**Comment by Shannon95** [comment]
After looking at the reference period dimension again on the above datasets I can see all associated ref periods  to each dataset can be filtered fine, however this takes a lot of scrolling as it seems to currently show all available reference periods across trade datasets ?

**Comment by jennet** [comment]
Will be covered by #42
