### ISSUE TITLE
Update ons-fdi  Data Set 

### ISSUE THREAD

**Issue by VTula2000** [Swirrl/ons-data-export#16]
- [ ] Need to update with latest version of PMD3 
http://cogs-staging-web.swirrlstaging.com/dataset/cube?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-fdi-catalog-entry

**Comment by JasonHowell** [comment]
The FDI was modified on the 14th Apr and therefore the dataset needs to be refreshed from PMDv3.  
Thanks
Jason.

**Comment by jennet** [comment]
Has the URI for this dataset changed? I can't see a dataset with the slug `ons-di` on https://gss-cogs.github.io/family-trade/datasets/

**Comment by jennet** [comment]
see https://github.com/Swirrl/ons-data-export/issues/39#issuecomment-620008485

**Comment by jennet** [comment]
Updated on cogs-staging http://cogs-staging-web.swirrlstaging.com/dataset/cube?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-fdi-catalog-entry

**Comment by JasonHowell** [comment]
@jennet believe this one can now be closed down.  Thanks.
