### ISSUE TITLE
UK Regional Trade Statistics (RTS) CSV Download Inconsistency 

### ISSUE THREAD

**Issue by RedWalters** [Swirrl/ons-data-export#19]
UK Regional Trade Statistics (RTS) displays correctly in PMD3 and PMD4 with 4889890 lines, however when the CSV is downloaded - with no filters - in PMD4 only 4063288 lines are outputted. 

Unsure if this issue is present in PMD3 as the download currently doesn't work, possible due to the size of the data set.

**Comment by jennet** [comment]
See details on #44 

The cogs-staging saved downloads from old versions of the dataset have now been cleared
