### ISSUE TITLE
Typo in price classifications configuration

### ISSUE THREAD

**Issue by jennet** [Swirrl/ons-data-export#21]
components.csv has the code list URI set to `http://gss-data.org.uk/def/concept-scheme/price-classification` however the actual URI of the concept scheme is `http://gss-data.org.uk/def/concept-scheme/price-classifications`

https://github.com/GSS-Cogs/family-trade/blob/master/reference/components.csv#L14

**Comment by JasonHowell** [comment]
@jennet believe this one can now be closed down.  Thanks.

**Comment by jennet** [comment]
This is still a problem in the extract #50, might be caused by stale data in PMD3

@ajtucker Shall we delete the offending triples from the PMD3 database directly?

**Comment by ajtucker** [comment]
I think I've managed to remove all these stale statements now.
