### ISSUE TITLE
Multiple labels being brought through for dimensions

### ISSUE THREAD

**Issue by jennet** [Swirrl/ons-data-export#24]
This is likely to be caused by stale data in PMD3 as with issue #22 

If a dimension has more than one label then its display in the dimension picker will not be very pretty as it shows the raw data.

Whenever new data is reimported from PMD3 it reintroduces the multiple labels for the following dimensions

dimension | label
-- | --
http://purl.org/linked-data/cube#measureType | "Measure Type"@en
http://purl.org/linked-data/cube#measureType | "measure type"@en
http://purl.org/linked-data/sdmx/2009/dimension#refPeriod | "Period"@en
http://purl.org/linked-data/sdmx/2009/dimension#refPeriod | "Reference Period"@en
http://gss-data.org.uk/def/dimension/flow | "Flow"@en
http://gss-data.org.uk/def/dimension/flow | "Flow"
http://gss-data.org.uk/def/dimension/trade-partner-geography | "Trade Partner Geography"
http://gss-data.org.uk/def/dimension/trade-partner-geography | "HMRC Partner Geography"@en
http://gss-data.org.uk/def/dimension/product | "SITC 4"@en
http://gss-data.org.uk/def/dimension/product | "Product"
http://gss-data.org.uk/def/dimension/trade-reporter-geography | "Trade Reporter Geography"
http://gss-data.org.uk/def/dimension/trade-reporter-geography | "HMRC Reporter Region"@en

**Comment by jennet** [comment]
> Are the extra labels for those two cube-vocab dimensions introduced by us?

We (Swirrl) haven't added any labels, I think this looks more like a configuration changes with the old labels not being removed from the PMD3 database.

If you're referring to the additional dimensions that we have added as part of #23, then nope - these aren't from there.

**Comment by jennet** [comment]
There was a suggestion that ONS may flush the components graph when new data is added? This would suggest that there's mismatches in the config / between datasets that produces the multiple labels

**Comment by Robsteranium** [comment]
I'm not sure where a second label for `qb:measureType` or `sdmx-dim:refPeriod` could've come from. I've just check the vocab and there should only be one label for each (and it's not been changed since 2013 afaik). Perhaps someone tried to re-create those with the components-pipeline?

I can't seem to find either of those two 2nd labels now so I guess they've since been deleted. If they show up again it would be interesting to know which graph they're in. Third party vocabs will probably be in their own graph (looks like this has changed too since I bootstrapped with ons-table2qb) while the ONS components should be in http://gss-data.org.uk/graph/components.

**Comment by ajtucker** [comment]
I only just got to this issue, but did track down and clear out a load of multiple labels last week.

The "measure type" duplicate sneaked its way in while working on the large datasets where we're doing CSV2RDF directly and embedding the DSD in the JSON-LD as per the [W3C example](https://github.com/w3c/csvw/blob/gh-pages/examples/rdf-data-cube-example.md) as well as wanting to pass the Data Cube ICs.

Passing the ICs for a direct CSV2RDF transform requires some duplicated definitions in the DSD, but the `rdfs:label`s for properties were overkill and I've removed them.

The other multiple labels came from changing definitions in various `components.csv` files and not (being able to) clearing the previous RDF out before updating in PMD.

```
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  { ?p a qb:DimensionProperty } UNION
  { ?p a qb:MeasureProperty } UNION
  { ?p a qb:AttributeProperty }
  ?p rdfs:label ?l1, ?l2 .
  FILTER (?l1 != ?l2) .
}
```

This currently shows up only `http://gss-data.org.uk/def/measure/median-months` as having more than one label.

**Comment by JasonHowell** [comment]
@jennet believe this one can now be closed down.  Thanks.

**Comment by jennet** [comment]
This happened in today's extract - the flow dimension had two labels: Flow and Flow Directions.

Leaving open for now

**Comment by ajtucker** [comment]
The reference-data Jenkins pipeline now uses CSV2RDF directly, letting us a) declare that URI of the component separately from the label, potentially including prefixes for family or dataset specific components, b) declare property hierarchies, c) put the resulting definitions into their own graph.

This should fix the multiple labels issue.

**Comment by jennet** [comment]
Flow dimension label should be "Flow"

Querying the db directly confirms there are no labels other than this.
