### ISSUE TITLE
HMRC RTS Small area errors

### ISSUE THREAD

**Issue by VTula2000** [Swirrl/ons-data-export#25]
- [ ] PMDv4 Filter errors in following dimensions 

  - HMRC Partner Geography, SITC4, Reference Period

- [ ] Variation in naming Dimension titles PMD3 vs PMDv4

 -PMD3 - Trade reporter geography,	Trade partner geography,   Product
 -PMD4 - HMRC reporter region, 	HMRC Partner Geography,  SITC 4

http://cogs-staging-web.swirrlstaging.com/dataset/cube?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc-rts-small-area-catalog-entry&order-by-component=http%253A%252F%252Fgss-data.org.uk%252Fdef%252Fdimension%252Ftrade-partner-geography&order-direction=DESC&

**Comment by jennet** [comment]
This is most likely due to issues #23 and #24

**Comment by jennet** [comment]
@VTula2000 could you confirm whether you are finding errors in the UI (e.g. something is crashing/bugging out) or whether the errors are unexpected data / data mismatches

**Comment by jennet** [comment]
Dataset slug: `hmrc-rts-small-area`
Dimension: HMRC Partner Geography
Code list: ONS Trade Areas CORD
Problem: all values are greyed out, i.e. the specified code list is not correct for the values in the data

Action: JW to investigate if this is due to the Swirrl data adjustments or a configuration problem.

**Comment by jennet** [comment]
Dataset slug: hmrc-rts-small-area
Dimension: SITC 4
Code list: SITC 4
Problem: many greyed out codes, but there are active ones. This is more of a data modelling / UI discussion in that there are many more options in the code list than are used in the data, which makes the filter dialog unweildy

![Screenshot 2020-04-22 at 14 15 50](https://user-images.githubusercontent.com/4940135/79986491-087af400-84a4-11ea-91b8-c3e86ebdf536.png)

**Comment by jennet** [comment]
Dataset slug: hmrc-rts-small-area
Dimension: Reference Period
Code list: Reference Period
Problem: many greyed out codes, but there are active ones. This is more of a data modelling (of code lists) / UI discussion in that there are many more options in the code list than are used in the data, which makes the filter dialog unweildy

![Screenshot 2020-04-22 at 14 24 10](https://user-images.githubusercontent.com/4940135/79987190-ffd6ed80-84a4-11ea-9b56-2c33b8210637.png)

**Comment by jennet** [comment]
Dataset slug: hmrc-rts-small-area

Label mismatches. 

PMD3 | PMD4 | Reason 
-- | -- | --
Trade reporter geography | HMRC reporter region | Wrong label chosen as a data fix to #24
Trade partner geography | HMRC Partner Geography | Wrong label chosen as a data fix to #24
Product | SITC 4 | New dimension created as part of #23 

Action - fix labels for Trade reporter geography, Trade partner geography

Further info needed: Check with Bill/Alex etc to know what is the plan of action for the Product dimension

**Comment by jennet** [comment]
cc @VTula2000 I've added more info about the various issues above, and will let you know when I have adjusted the labels, and what I find out about the HMRC Partner Geography dimension

**Comment by jennet** [comment]
> Dataset slug: hmrc-rts-small-area
> Dimension: HMRC Partner Geography
> Code list: ONS Trade Areas CORD
> Problem: all values are greyed out, i.e. the specified code list is not correct for the values in the data
> Action: JW to investigate if this is due to the Swirrl data adjustments or a configuration problem.

There is a mismatch in the component / dimension settings, which appears to have been pulled from an earlier version of what is currently on PMD3, so a data update will most likely fix this problem

**Comment by jennet** [comment]
The most recent extraction of this dataset (2020-04-23) uses dimensions `http://gss-data.org.uk/def/dimension/hmrc-partner-geography` and `http://gss-data.org.uk/def/dimension/trade-reporter-geography` so the labels are displaying "HMRC Partner Geography" and "Trade Reporter Geography" as would be expected based on those dimensions, configuration would need to be adjusted in column.csv to change the components/dimensions used on this dataset

**Comment by jennet** [comment]
Dataset is in same status as last comment for extract #50 - i.e. the labels are showing the correct ones for the dimension specified in the dataset - any changes would need to be made in the source CSV / configuration.
