### ISSUE TITLE
Updated version : UK trade in goods, CPA (08)

### ISSUE THREAD

**Issue by Shannon95** [Swirrl/ons-data-export#26]
CDID dimension has been added to the transformation of this dataset: 
http://gss-data.org.uk/dataset?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-uk-trade-in-goods-cpa-08

Could PMDv4 be updated with the latest version please.

**Comment by jennet** [comment]
done as part of #33
