### ISSUE TITLE
No link available to the original website landing page

### ISSUE THREAD

**Issue by mikeAdamss** [Swirrl/ons-data-export#28]
No link available to the original website landing page, should we have one? 

(example: ONS-UK-trade-in-goods-by-industry-country-and-commodity)

**Comment by JasonHowell** [comment]
@jennet caught up with Mike and believe this issue should be moved to the new Swirrl issues repo.   The details should be in the about page and following field  dcat:landingPage?

**Comment by BillSwirrl** [comment]
closing this (without transferring to cogs-issues) as all published datasets do now have a landingPage link
