### ISSUE TITLE
Overriding Value column label

### ISSUE THREAD

**Issue by mikeAdamss** [Swirrl/ons-data-export#29]
Overriding Value column label,(example: ONS-UK-trade-in-goods-by-industry-country-and-commodity, we’re using “GBP Total”).

This has been questioned by our BA's. Should we be doing this? How/why/where is the mechanism?

**Comment by jennet** [comment]
@mikeAdamss  Is this a question for Swirrl? If so, could you provide a bit more context?

**Comment by mikeAdamss** [comment]
apologies, didn't see the comment.

this dataset: http://cogs-staging-web.swirrlstaging.com/dataset/cube?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-trade-in-goods-catalog-entry

has the observation column label "GBP Total" where in pmd3 it has the observation column label "Value" and our Business Analysts have questioned whether it's correct as they find it confusing.

**Comment by jennet** [comment]
@mikeAdamss in PMD4 if a observation column is a measure, then it displays the label of that specific measure rather than a generic "value" in the column header.
In this particular case, that column (component) is configured to use the measure `http://gss-data.org.uk/def/measure/gbp-total`

**Comment by mikeAdamss** [comment]
@jennet - fair enough and thanks for the info. As its intended behaviour I'll go back with that, if it's an issue for them I'm sure they'll raise it. Closing this one.
