### ISSUE TITLE
International exports of services - Not on pmd4 & one line only csv download on pmd3

### ISSUE THREAD

**Issue by mikeAdamss** [Swirrl/ons-data-export#30]
Have put two issues on this card as tbh, if it works on pmd4 we don't care that much about pmd3 downloads.

Currently these are missing from pmd4 and showing a download of only one lines on pmd3.

`International exports of services from joint authority areas of the UK`

`International exports of services from subnational areas of the UK`

**Comment by jennet** [comment]
[International exports of services from joint authority areas of the UK](http://cogs-staging-web.swirrlstaging.com/dataset/cube?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-exports-of-services-from-subnational-areas-of-the-uk%2FobservationsJointAuthority-catalog-entry)

downloaded CSV checked as having 540 records

[International exports of services from subnational areas of the UK](http://cogs-staging-web.swirrlstaging.com/dataset/cube?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-exports-of-services-from-subnational-areas-of-the-uk-catalog-entry)

downloaded CSV checked as having 2550 records

Note: there is a third dataset with a duplicate title - http://cogs-staging-web.swirrlstaging.com/dataset/cube?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-exports-of-services-from-subnational-areas-of-the-uk%2FobservationsNUTS-catalog-entry
