### ISSUE TITLE
Error retrieving data from PMD3: MRETS: Product 

### ISSUE THREAD

**Issue by jennet** [Swirrl/ons-data-export#31]
Dataset: `ons_mrets/mrets-product`
Row 23 on https://gss-cogs.github.io/family-trade/datasets/

http://gss-data.org.uk/resource?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons_mrets%2Fmrets-product

**Comment by JasonHowell** [comment]
@jennet believe this one can now be closed down.  Thanks.
