### ISSUE TITLE
Error retrieving data from PMD3 for dataset Quarterly Balance of Payments: Trade in services

### ISSUE THREAD

**Issue by jennet** [Swirrl/ons-data-export#32]
Dataset: `ons_bop/quarterly-balance-of-payments-trade-in-services`
Row 20 of https://gss-cogs.github.io/family-trade/datasets/

http://gss-data.org.uk/resource?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons_bop%2Fquarterly-balance-of-payments-trade-in-services

**Comment by JasonHowell** [comment]
@jennet believe this one can now be closed down.  Thanks.
