### ISSUE TITLE
Very long comment on dataset International exports of services from joint authority areas of the UK

### ISSUE THREAD

**Issue by jennet** [Swirrl/ons-data-export#36]
This size of comment would be better as the dataset description

**Comment by Robsteranium** [comment]
The text also enumerates a lot of codes, perhaps it would be sufficient to link to the codelists?

Bits like this would be good to have on the codelist itself too:
> The industrial groups presented in this analysis are based on the UK Standard Industrial Classification 2007, although some changes have been made. Non-manufacturing production services represents SIC07 section A, B, D, E and F; section G has been split into two parts (Wholesale and motor trades, and Retail); Other services comprises of L, O, P, Q, R, S and unknown/unallocated industries.

**Comment by jennet** [comment]
closed in #52
