### ISSUE TITLE
Create RDF extra metadata from Word documents of dataset details

### ISSUE THREAD

**Issue by jennet** [Swirrl/ons-data-export#40]
Rob's [dataset lookup CSV](https://github.com/Swirrl/ons-data-export/blob/master/metadata/dataset_lookup.csv) helps match the supplied Word files to the datasets that are published.

- [x] create RDF from information contained in the Word files
- [x] add to cogs-staging datasets

**Comment by jennet** [comment]
- [ ] Foreign direct investment involving UK companies: inward
- [ ] Overseas Trade Statistics (CN8)
- [ ] International exports of services from subnational areas of the UK
- [ ] REGIONAL TRADE STATISTICS
- [ ] MRETS
- [ ] HMRC UK Trade in Goods Statistics by Business Characteristics 2015
- [ ] UK Ecconomic Accounts; balance of payments - current account
- [ ] UK trade in goods by classification of product by activity time series
- [ ] Trade in goods: country-by-commodity imports
- [ ] UK trade in goods by industry, country and commodity, exports
- [ ] Trade in goods: country-by-commodity imports
- [ ] UK trade in services: service type by partner country, non-seasonally adjusted
- [ ] 03 Trade in services, The Pink Book
- [ ] Annual Business Survey exporters and importers

**Comment by jennet** [comment]
Noticed that in the lookup file, both `20190916 - UK Trade in goods by country and commodity.docx` and `20190916 - UK Trade in goods by country.docx` have the same dataset listed: `Trade in goods: country-by-commodity imports`

**Comment by jennet** [comment]
- Overseas Trade Statistics (CN8)
- HMRC UK Trade in Goods Statistics by Business Characteristics 2015
- UK Ecconomic Accounts; balance of payments - current account
- UK trade in goods by industry, country and commodity, exports

Are not published - see https://gss-cogs.github.io/family-trade/datasets/

**Comment by jennet** [comment]
Moving back to backlog until any more of these datasets are published / more information is available

**Comment by JasonHowell** [comment]
Jen, if this is only about the data supplied for Trade, then I think this can be closed as that was a one off for Trade.  Trade portal is with the users so would expect them to give us feedback on the dataset information going forward.  Thanks

**Comment by BillSwirrl** [comment]
closing as agreed
