### ISSUE TITLE
Concepts with duplicate labels / comments / notations

### ISSUE THREAD

**Issue by jennet** [Swirrl/ons-data-export#49]
Most likely due to old data not getting deleted before updated labels etc being added. 

similar to #47

**Comment by jennet** [comment]
still a problem in #50 

`http://business.data.gov.uk/companies/def/sic-2007/scheme`

(see also #51 re labels in that scheme)

**Comment by ajtucker** [comment]
`http://business.data.gov.uk/companies/def/sic-2007/scheme` is taken directly from `http://business.data.gov.uk/companies/sources/vocab/sic-2007.ttl`. I've checked the SKOS constraints in https://github.com/GSS-Cogs/GDP-tests/tree/master/tests/sparql/skos and can't see any issues.

We did have issues with missing `rdfs:label`s for this concept scheme, so load up a separate graph with the labels: https://github.com/GSS-Cogs/GDP-vocabs/blob/master/vocabs/sic-2007-labels.ttl

I can no longer find any duplicate labels (or comments for that matter) for concepts:
```
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT * {
  ?c a skos:Concept ;
     rdfs:label ?l1, ?l2 .
  FILTER (?l1 != ?l2 && lang(?l1) = lang(?l2))
}
```

Do the multi-valued `skos:notation`s cause a problem for PMD4?

**Comment by jennet** [comment]
> Do the multi-valued skos:notations cause a problem for PMD4?

It's one of the validations in the PMD4 loader, but I will need to double check the impact of this

**Comment by jennet** [comment]
@ajtucker Are you running that query against the PMD3 database? I have just run it against the gss alpha db and it's returning multiple labels for `http://gss-data.org.uk/def/concept-scheme/product`

**Comment by ajtucker** [comment]
I'm attempting to guard against these issues, in this case using https://github.com/GSS-Cogs/family-trade/blob/master/tests/sparql/concept-at-most-one-label.sparql and a test-runner job in Jenkins, whose results are https://ci.floop.org.uk/job/GSS_data/job/Trade/job/tests/lastCompletedBuild/testReport/(root)/sparql/Concepts_should_have_at_most_one_label/

**Comment by jennet** [comment]
Moving placeholder for this issue over to https://github.com/Swirrl/cogs-issues/issues/13
