### ISSUE TITLE
Reduce 2 of International export datasets

### ISSUE THREAD

**Issue by JasonHowell** [Swirrl/ons-data-export#52]
The following datasets need to be removed as they are a duplicate as original dataset has been merged into one:

International exports of services from joint authority areas of the UK
http://cogs-staging-web.swirrlstaging.com/dataset/cube?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-exports-of-services-from-subnational-areas-of-the-uk%2FobservationsJointAuthority-catalog-entry

This has the longer description:
International exports of services from subnational areas of the UK
http://cogs-staging-web.swirrlstaging.com/dataset/cube?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-exports-of-services-from-subnational-areas-of-the-uk%2FobservationsNUTS-catalog-entry

**Comment by jennet** [comment]
http://cogs-staging-web.swirrlstaging.com/dataset/cube?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-exports-of-services-from-subnational-areas-of-the-uk-catalog-entry
