### ISSUE TITLE
Special characters not rendering in HTML

### ISSUE THREAD

**Issue by jennet** [Swirrl/ons-data-export#6]
HTML in the markdown description are coming through as raw text and displaying the codes in the browser 

<img width="1552" alt="Screenshot 2020-03-31 at 09 34 32" src="https://user-images.githubusercontent.com/4940135/78005038-ea9df180-7332-11ea-989d-e74a29caf2ff.png">

**Comment by RickMoynihan** [comment]
Can you provide the link to the offending page/dataset?

Also do we know where the markdown was generated?

**Comment by jennet** [comment]
@RickMoynihan 

Apologies, the metadata was removed accidentally as this is one of the datasets manually updated due to size and I missed the step to add the additional metadata.

In answer to your questions: 
this is the dataset =: http://cogs-staging-web.swirrlstaging.com/dataset/about?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc_rts-catalog-entry
I have not been able to clear the cache on the server, I'll check in with you about this tomorrow morning.

The markdown was generated manually by Bill

**Comment by jennet** [comment]
Closing this issue as it's now reported on PMD4 issues list
